### ISSUE TITLE
Test - missing graph

### ISSUE THREAD

**Issue by baktygulysabekova** [sustainabledevelopment-kyrgyzstan/open-sdg-data-starter#37]
17  goal missing graph (not really - TEST): https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-site-starter/TEST

Please review: https://stackoverflow.com/questions/37273337/chart-js-v2-line-chart-missing-point

**Comment by baktygulysabekova** [comment]
Fixed: https://github.com/sustainabledevelopment-kyrgyzstan/open-sdg-data-starter/pull/33

**Comment by Norric1Admin** [comment]
Fixed: https://github.com/sustainabledevelopment-kyrgyzstan/open-sdg-data-starter/pull/90 and https://github.com/sustainabledevelopment-kyrgyzstan/open-sdg-data-starter/pull/89
